name = "chatgpt-connector-time"
main = "src/index.ts"
compatibility_date = "2025-03-21"
compatibility_flags = [ "nodejs_compat" ]

# Optional: Enable observability features
[observability]
enabled = true
